version: '2.1'

services:
    
    # https://hub.docker.com/r/linuxserver/raneto
    raneto:
        image: linuxserver/raneto:latest
        volumes:
            - 'raneto:/config'
        labels:
            traefik.enable: true
            traefik.http.routers.raneto.entrypoints: https
            traefik.http.routers.raneto.tls.certresolver: tlschallenge
            traefik.http.routers.raneto.middlewares: secureheaders, basicauth
            subdomain: raneto

    # https://hub.docker.com/r/linuxserver/smokeping
    smokeping:
        image: linuxserver/smokeping:latest
        volumes:
            - 'smokeping:/config'
        labels:
            traefik.enable: true
            traefik.http.routers.smokeping.entrypoints: https
            traefik.http.routers.smokeping.tls.certresolver: tlschallenge
            traefik.http.routers.smokeping.middlewares: secureheaders, basicauth
            subdomain: smokeping

    # https://hub.docker.com/_/ghost/
    ghost:
        image: ghost:latest
        volumes:
            - 'ghost:/var/lib/ghost/content:rw'
        labels:
            traefik.enable: true
            traefik.http.routers.ghost.entrypoints: https
            traefik.http.routers.ghost.tls.certresolver: tlschallenge
            traefik.http.routers.ghost.middlewares: secureheaders, basicauth
            subdomain: ghost

    # https://hub.docker.com/r/linuxserver/duplicati
    duplicati:
        image: linuxserver/duplicati:latest
        container_name: duplicati
        volumes:
            - 'duplicati:/config:rw'
            - 'raneto:/source/raneto:ro'
            - 'smokeping:/source/smokeping:ro'
            - 'ghost:/source/ghost:ro'
        labels:
            traefik.enable: true
            traefik.http.routers.duplicati.entrypoints: https
            traefik.http.routers.duplicati.tls.certresolver: tlschallenge
            traefik.http.routers.duplicati.middlewares: secureheaders, basicauth
            subdomain: duplicati

    # https://hub.docker.com/_/traefik/
    traefik:
        image: traefik:latest
        ports:
            - '80:80/tcp'
            - '443:443/tcp'
        volumes:
            - 'traefik:/etc/traefik'
        environment:
            TRAEFIK_LOG_LEVEL: INFO
            TRAEFIK_API: true
            TRAEFIK_GLOBAL_SENDANONYMOUSUSAGE: false
            TRAEFIK_ENTRYPOINTS_HTTP_ADDRESS: :80
            TRAEFIK_ENTRYPOINTS_HTTPS_ADDRESS: :443
            TRAEFIK_PROVIDERS_DOCKER: true
            TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT: false
            TRAEFIK_PROVIDERS_DOCKER_ENDPOINT: unix:///var/run/balena.sock
            TRAEFIK_CERTIFICATESRESOLVERS_TLSCHALLENGE_ACME_TLSCHALLENGE: true
            TRAEFIK_CERTIFICATESRESOLVERS_TLSCHALLENGE_ACME_STORAGE: /etc/traefik/acme.json
            # TRAEFIK_CERTIFICATESRESOLVERS_TLSCHALLENGE_ACME_CASERVER: https://acme-staging-v02.api.letsencrypt.org/directory
        labels:
            io.balena.features.balena-socket: true
            traefik.enable: true
            traefik.http.routers.traefik.entrypoints: https
            traefik.http.routers.traefik.tls.certresolver: tlschallenge
            traefik.http.routers.traefik.middlewares: secureheaders, basicauth
            traefik.http.routers.traefik.service: api@internal
            traefik.http.routers.http.entrypoints: http
            traefik.http.routers.http.rule: HostRegexp(`{catchall:.+}`)
            traefik.http.routers.http.middlewares: redirectscheme
            traefik.http.middlewares.redirectscheme.redirectscheme.scheme: https
            traefik.http.middlewares.basicauth.basicauth.usersfile: /etc/traefik/.htpasswd
            traefik.http.middlewares.secureheaders.headers.stsSeconds: 15552000
            traefik.http.middlewares.secureheaders.headers.framedeny: true
            traefik.http.middlewares.secureheaders.headers.sslForceHost: true
            traefik.http.middlewares.secureheaders.headers.sslRedirect: true
            traefik.http.middlewares.secureheaders.headers.stsIncludeSubdomains: true
            traefik.http.middlewares.secureheaders.headers.browserXssFilter: true
            traefik.http.middlewares.secureheaders.headers.contentTypeNosniff: true
            traefik.http.middlewares.secureheaders.headers.forceSTSHeader: true
            traefik.http.middlewares.secureheaders.headers.stsPreload: true
            traefik.http.middlewares.secureheaders.headers.customResponseHeaders.X-Robots-Tag: none
            traefik.http.middlewares.secureheaders.headers.customFrameOptionsValue: SAMEORIGIN
            subdomain: traefik

    # https://hub.docker.com/r/containous/whoami
    whoami:
        image: containous/whoami:latest
        labels:
            traefik.enable: true
            traefik.http.routers.whoami.entrypoints: https
            traefik.http.routers.whoami.tls.certresolver: tlschallenge
            traefik.http.routers.whoami.middlewares: secureheaders, basicauth
            subdomain: whoami

volumes:
    duplicati:
    raneto:
    smokeping:
    traefik:
    ghost:
